---

# Override default role variables here.

# dock items
# ------------------------------------------------------------------------------

dock_apps:
  - Skype.app
  - Google Chrome.app
  - Evernote.app
  - Skitch.app
  - Calendar.app
  - Wunderlist.app
  - System Preferences.app

# login items
# ------------------------------------------------------------------------------

login_items_apps:
  - Alfred 3.app
  - CrasPlan menu bar.app
  - Dropbox.app
  - Flux.app
  - Google Photos Backup.app
  - HazelHelper.app
